### PR TITLE
exhaustingly done

### PR DESCRIPTION
**Pull request by zzmtsvv**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey.

The devil is in the detail(s).

2.1 Sometimes task do not provide all bounds, since they are obvious (marks have to be in the range from 2 to 5 and integers!)
image

2.2 The same

Do not use static modificator in the structures and classes, please. Static breaks encapsulation and keep the memory in the stack. Stack is limited (by 1Mb) and a lot of static fields in the samples of the structures or classes overflow it (in any language).
image
image

Moreover, private static - it is like turtule with a glass shell. Use static methods only in the starting class (I mean where main() presents). 

I hope you know how does it works:
StudentsComparer : IComparer<Student>
IOrderedEnumerable<SkiAthlete> xx = x.OrderBy(g => g.sum);

3.6 Why did you check it?
if (s1 == "")
                    {
                        s1 = null;
                    }
if in the end you still check it again?
 if (s1 == s2 && s2 == s3 && s3 == null)
                    {
                        break;
                    }
Why do not break immediatelly, isn't it?

It is bad practice to get access to the fields directly:
                List<string> arr1 = Survey.Answer1;
                List<string> arr2 = Survey.Answer2;
                List<string> arr3 = Survey.Answer3;
Very seldom it is really neccessary.

image
image

**Comment by zzmtsvv** [comment]
Ok, I got it
The only issue I have is why can't I use marks as numbers with floating point? Like "ballno-raitingovaya sistema"? nonetheless, they still must be in range from 2 to 5

**Comment by zzmtsvv** [comment]
3.6 there might be cases when one or two are nulls while the third one isn't so I must check when they are all null at the same time to break out of the loop

**Comment by NemirovichMark** [comment]
Since you count average instead of sum, it seems like traditional system. And 2100 had being written in 2014-2015, so... it is defenatelly traditional system ment)

3.6 Oh, so you do it as a finish... okay. I thought such person should be skiped (till 5 answers would received). I accept it. But another remarks are stay with you.

**Comment by zzmtsvv** [comment]
Should I rewrite all the stuff with static modificators or I can leave it the way it is?
Screenshot 2022-10-26 at 11 58 55

**Comment by zzmtsvv** [comment]
do you want me to remove static modificators? if yes, so what is the another way to solve the problem using structures? can you give me a conceptual hint

**Comment by NemirovichMark** [comment]
Hello Alexey.

Yes, I want you reduce static usage. Static methods and fields lives all time you program work: from launching to exit. And they take up memory on the stack.
So you can instantiate the struct and call its public methods or fields instead. 

image

You can also use enum for some constants.

**Comment by NemirovichMark** [comment]
You can come to class to defend 6rd lab.
I will give you more difficult task in the class. So read the theory I wrote about on the GitHub.

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/7th_Lab

**Pull request merged**
